apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-api-config
  namespace: fcg
data:
  ASPNETCORE_ENVIRONMENT: Production

  RabbitMQ__Host: rabbitmq
  RabbitMQ__Port: "5672"

  RabbitMQ__Queues__FCG_User: FCG-user-queue

