apiVersion: v1
kind: Service
metadata:
  name: notifications-api-service
  namespace: fcg

spec:
  selector:
    app: notifications-api

  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30030

  type: NodePort