apiVersion: v1
kind: Secret
metadata:
  name: payments-api-secret
  namespace: fcg
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "server=mysql;port=3306;database=fcgdb;user=root;password=root123"

  RabbitMQ__Username: guest
  RabbitMQ__Password: guest