apiVersion: v1
kind: ConfigMap
metadata:
  name: users-api-configmap
  namespace: fcg
data:
  ASPNETCORE_ENVIRONMENT: Production

  RabbitMQ__Host: rabbitmq
  RabbitMQ__Port: "5672"

  RabbitMQ__Queues__FGC: FGC-queue

