services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: fcgdb

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  users-api:
    build:
      context: ../../
      dockerfile: UserAPI-master/UsersAPI/Dockerfile
    image: users-api:latest

    restart: always

    environment:
      ConnectionStrings__DefaultConnection: "server=mysql;port=3306;database=fcgdb;user=root;password=root123"
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
      RabbitMQ__Queues__FCG_User: FCG-queue-user

    ports:
      - "8010:8080"

    depends_on:
      - mysql

    networks:
      - app-network
  
  notifications-api:
    build: 
      context: ../../
      dockerfile: NotificationsAPI-master/NotificationsAPI/Dockerfile
    image: notifications-api:latest

    restart: always

    environment:
      ConnectionStrings__DefaultConnection: "server=mysql;port=3306;database=fcgdb;user=root;password=root123"
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
      
      RabbitMQ__Queues__FCG_User: FCG-queue-user      
      RabbitMQ__Queues__FCG_Catalog: FGC-queue-catalog
      RabbitMQ__Queues__FCG_Payment: FGC-queue-payment
      API_Users__URL: http://users-api:8080
      API_Users__Email: admin@email.com
      API_Users__Senha: 1234@Abc
      URL_API_Catalog: http://catalog-api:8080 

    ports:
      - "8020:8080"

    networks:
      - app-network

    depends_on:
      - rabbitmq

  catalog-api:
    build: 
      context: ../../
      dockerfile: CatalogAPI-master/CatalogAPI/Dockerfile
    image: catalog-api:latest

    restart: always

    environment:
      ConnectionStrings__DefaultConnection: "server=mysql;port=3306;database=fcgdb;user=root;password=root123"
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
      
      RabbitMQ__Queues__FCG_Catalog: FGC-queue-catalog
      RabbitMQ__Queues__FCG_Payment: FGC-queue-payment

    ports:
      - "8030:8080"

    depends_on:
      - mysql

    networks:
      - app-network

  payments-api:
    build: 
      context: ../../
      dockerfile: PaymentAPI-master/PaymentsAPI/Dockerfile
    image: payments-api:latest
    
    restart: always

    ports:
      - "8040:8080"

    environment:
      ConnectionStrings__DefaultConnection: "server=mysql;port=3306;database=fcgdb;user=root;password=root123"
      
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
      
      RabbitMQ__Queues__FCG_Catalog: FGC-queue-catalog
      RabbitMQ__Queues__FCG_Payment: FGC-queue-payment

    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Porta AMQP
      - "15672:15672" # Painel web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

    networks:
      - app-network

volumes:
  mysql_data:  

networks:
 app-network:
   driver: bridge