services:
  mysql:
    image: mysql:8.4
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: fcgdb

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  users-api:
    build: 
      context: ../../UsersAPI
    image: users-api:latest
    ports:
      - "8010:8080"
  
  notifications-api:
    build: 
      context: ../../NotificationsAPI
    image: notifications-api:latest
    ports:
      - "8020:8080"
  
  catalog-api:
    build: 
      context: ../../CatalogAPI
    image: catalog-api:latest
    ports:
      - "8030:8080"

  payments-api:
    build: 
      context: ../../PaymentsAPI
    image: payments-api:latest
    ports:
      - "8040:8080"

volumes:
  mysql_data: