name: fgc

services:
  mysql:
    container_name: mysql

    image: mysql:8.4

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: fcgdb

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - app-network

  rabbitmq:
    container_name: rabbitmq
    
    image: rabbitmq:4.3.1-management
    
    ports:
      - "5672:5672"   # Porta AMQP
      - "15672:15672" # Painel web
    
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - app-network

  users-api:
    container_name: users-api

    build:
      context: ../../UsersAPI
      dockerfile: Dockerfile
      
    image: users-api:latest

    restart: always

    environment:
      ConnectionStrings__DefaultConnection: "server=mysql;port=3306;database=fcgdb;user=root;password=root123"
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
      RabbitMQ__Queues__FCG_User: FCG-queue-user

    ports:
      - "8010:8080"

    depends_on:
      - mysql

    networks:
      - app-network
  
  # notifications-api:
  #   container_name: notifications-api
      
  #   build: 
  #     context: ../../NotificationsAPI
  #     dockerfile: Dockerfile
      
  #   image: notifications-api:latest

  #   restart: always

  #   environment:
  #     ConnectionStrings__DefaultConnection: "server=mysql;port=3306;database=fcgdb;user=root;password=root123"
      
  #     RabbitMQ__Host: rabbitmq
  #     RabbitMQ__Port: 5672
  #     RabbitMQ__Username: guest
  #     RabbitMQ__Password: guest
      
  #     RabbitMQ__Queues__FCG_User: FCG-queue-user      
  #     RabbitMQ__Queues__FCG_Notification: FGC-queue-notification
      
  #     API_Users__URL: http://users-api:8080
  #     API_Users__Email: admin@email.com
  #     API_Users__Senha: 1234@Abc
      
  #     URL_API_Catalog: http://catalog-api:8080 

  #   ports:
  #     - "8020:8080"

  #   networks:
  #     - app-network

  #   depends_on:
  #     - rabbitmq

  catalog-api:
    container_name: catalog-api
  
    build: 
      context: ../../CatalogAPI
      dockerfile: Dockerfile
      
    image: catalog-api:latest

    restart: always

    environment:
      ConnectionStrings__DefaultConnection: "server=mysql;port=3306;database=fcgdb;user=root;password=root123"
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
      
      RabbitMQ__Queues__FCG_Catalog: FGC-queue-catalog
      RabbitMQ__Queues__FCG_Payment: FGC-queue-payment

    ports:
      - "8030:8080"

    depends_on:
      - mysql

    networks:
      - app-network

  payments-api:
    container_name: payments-api
    
    build: 
      context: ../../PaymentsAPI
      dockerfile: Dockerfile
      
    image: payments-api:latest
    
    restart: always

    ports:
      - "8040:8080"

    environment:
      ConnectionStrings__DefaultConnection: "server=mysql;port=3306;database=fcgdb;user=root;password=root123"
      
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
      
      RabbitMQ__Queues__FCG_Catalog: FGC-queue-catalog
      RabbitMQ__Queues__FCG_Payment: FGC-queue-payment
      RabbitMQ__Queues__FCG_Notification: FGC-queue-notification

    networks:
      - app-network
  localstack:
    container_name: localstack
    image: localstack/localstack-pro:latest

    ports:
      - "4566:4566"

    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - SERVICES=lambda,sqs,iam,logs
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1

    volumes:
      - "./localstack:/var/lib/localstack"
      - "./localstack/init/ready.d:/etc/localstack/init/ready.d"
      - "./localstack/lambdas/NotificationsLambda.zip:/lambda/NotificationsLambda.zip:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"

    networks:
      - app-network

  rabbitmq-lambda-bridge:
    container_name: rabbitmq-lambda-bridge

    build:
      context: ../../RabbitMqLambdaBridge
      dockerfile: Dockerfile

    image: rabbitmq-lambda-bridge:latest

    environment:
      RABBITMQ_HOST: rabbitmq
      LOCALSTACK_URL: http://localstack:4566

    depends_on:
      rabbitmq:
        condition: service_healthy
      localstack:
        condition: service_healthy

    networks:
      - app-network

    restart: unless-stopped

volumes:
  mysql_data:  

networks:
 app-network:
   driver: bridge

