apiVersion: v1
kind: Secret
metadata:
  name: fcg-jwt-secret
  namespace: fcg
type: Opaque
stringData:
  # Em producao, substitua este valor por um secret gerenciado e nao versionado.
  secret-key: "8fR!D@Qk7S$5yHnWZ^mC0JbE%T2P9A4xL#V"
