apiVersion: v1
kind: Secret
metadata:
  name: kong-secret
  namespace: fcg
type: Opaque
stringData:
  postgres-user: kong
  postgres-password: kong
  postgres-database: kong
  konga-database: konga
  konga-token-secret: konga
