apiVersion: batch/v1
kind: Job
metadata:
  name: konga-prepare
  namespace: fcg
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        app: konga-prepare
    spec:
      restartPolicy: OnFailure
      containers:
        - name: konga-prepare
          image: pantsel/konga:latest
          imagePullPolicy: IfNotPresent
          args:
            - -c
            - prepare
            - -a
            - postgres
            - -u
            - postgresql://kong:kong@kong-database:5432/konga
