apiVersion: v1
kind: Service
metadata:
  name: kong-database
  namespace: fcg
spec:
  selector:
    app: kong-database
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  type: ClusterIP
