apiVersion: v1
kind: Secret
metadata:
  name: notifications-api-secret
  namespace: fcg
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "server=mysql;port=3306;database=fcgdb;user=root;password=root123"

  RabbitMQ__Username: guest
  RabbitMQ__Password: guest

  API_Users__Email: admin@email.com
  API_Users__Senha: 1234@Abc