{
 "title": "API - Contagem Requisições",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "label": "API", "query": "catalog-api, users-api" },
   {
    "name": "route",
    "label": "Endpoint",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{job=~\"$job\"}, http_route)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total de requisições",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{job=~\"$job\", http_route=~\"$route\"}[$__range]))"
    }
   ]
  },
  {
   "title": "HTTP 2xx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{job=~\"$job\", http_route=~\"$route\", http_response_status_code=~\"2..\"}[$__range])) or vector(0)"
    }
   ]
  },
  {
   "title": "HTTP 3xx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{job=~\"$job\", http_route=~\"$route\", http_response_status_code=~\"3..\"}[$__range])) or vector(0)"
    }
   ]
  },
  {
   "title": "HTTP 4xx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{job=~\"$job\", http_route=~\"$route\", http_response_status_code=~\"4..\"}[$__range])) or vector(0)"
    }
   ]
  },
  {
   "title": "HTTP 5xx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{job=~\"$job\", http_route=~\"$route\", http_response_status_code=~\"5..\"}[$__range])) or vector(0)"
    }
   ]
  },
  {
   "title": "Contagem por status HTTP",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, http_response_status_code) (increase(http_server_request_duration_seconds_count{job=~\"$job\", http_route=~\"$route\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Contagem por endpoint e status HTTP",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, http_route, http_request_method, http_response_status_code) (increase(http_server_request_duration_seconds_count{job=~\"$job\", http_route=~\"$route\"}[$__range]))"
    }
   ]
  }
 ]
}